version: '3'
 
services:
  database:
    image: mariadb:10.8
    container_name: database-exemplo
    environment:
      MARIADB_ROOT_PASSWORD: my_secret_password
      MARIADB_DATABASE: app_db
      MARIADB_USER: db_user
      MARIADB_PASSWORD: db_user_pass
    ports:
      - "6033:3306"
    volumes:
      - exemplo-mariadb-data:/var/lib/mysql
volumes:
  exemplo-mariadb-data: